# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "lapidary"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kenji Hara"]
  s.date = "2013-01-05"
  s.description = "Helper for creating RubyGem project"
  s.email = "haracane@gmail.com"
  s.executables = ["lapidary"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/lapidary",
    "lapidary.gemspec",
    "lib/lapidary.rb",
    "lib/lapidary/command/build.rb",
    "lib/lapidary/templates/.document.erb",
    "lib/lapidary/templates/.gitignore.erb",
    "lib/lapidary/templates/.rspec.erb",
    "lib/lapidary/templates/Gemfile.erb",
    "lib/lapidary/templates/LICENSE.txt.erb",
    "lib/lapidary/templates/README.rdoc.erb",
    "lib/lapidary/templates/Rakefile.erb",
    "lib/lapidary/templates/bin/project.erb",
    "lib/lapidary/templates/lib/project.rb.erb",
    "lib/lapidary/templates/spec/lib/project_spec.rb.erb",
    "lib/lapidary/templates/spec/spec_helper.rb.erb",
    "spec/bin/lapidary_spec.rb",
    "spec/lib/lapidary_spec.rb",
    "spec/reports/SPEC-Lapidary.xml",
    "spec/reports/SPEC-bin-lapidary.xml",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/haracane/lapidary"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Helper for creating RubyGem project"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_runtime_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_runtime_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_runtime_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<ci_reporter>, [">= 1.7.0"])
      s.add_runtime_dependency(%q<flog>, [">= 3.2.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ci_reporter>, [">= 1.7.0"])
      s.add_dependency(%q<flog>, [">= 3.2.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ci_reporter>, [">= 1.7.0"])
    s.add_dependency(%q<flog>, [">= 3.2.0"])
  end
end

